// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqtgbspxeoukwahhacld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xdGdic3B4ZW91a3dhaGhhY2xkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzOTExNTcsImV4cCI6MjA2MDk2NzE1N30.CSv2RjJ5zCk9ta_vSelIzpWJhTb1sMBy3NDoMDBfwoA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);