// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhldprnmhunbiitjxcnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpobGRwcm5taHVuYmlpdGp4Y25mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMjU0MjgsImV4cCI6MjA2MDkwMTQyOH0.sbn-CnlATMdwR9NhaLaPMAgshHuVZZw3RaRPpW2UU-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);